site_name: Exchange API Docs
nav:
    - GENERAL INFO: index.md
    - WALLET: account.md
    - MARKET DATA: Market_Data.md 
    - SPOT ACCOUNT/TRADE: spot.md 
    - MARGIN TRADE: Margin.md
    - ERROR INFO: error_info.md
     
theme: readthedocs
#theme: windmill
#extra_css: [extra.css]
